version: 2
job_common: &job_common
  docker:
    - image: circleci/node:10.15.0
  working_directory: ~/torus-website/app
step_save_cache: &step_save_cache
  save_cache:
    key: dependency-cache-{{ checksum "package.json" }}
    paths:
      - node_modules
step_restore_cache: &step_restore_cache
  restore_cache:
    key: dependency-cache-{{ checksum "package.json" }}
step_setup_global_packages: &step_setup_global_packages
  run:
    name: "Set up global packages"
    command: |
      sudo apt-get install -y libx11-xcb1 libxrandr2 libasound2 libpangocairo-1.0-0 libatk1.0-0 libatk-bridge2.0-0 libgtk-3-0 libnss3 libxss1 && npm install

jobs:
  build:
    <<: *job_common
    steps:
      - checkout:
          path: ~/torus-website
      - <<: *step_restore_cache
      - <<: *step_setup_global_packages
      - run:
          name: "Build code for torus website"
          command: npm run build
      - persist_to_workspace:
          root: ~/torus-website/
          paths:
            - app
      - <<: *step_save_cache
  unit-test:
    <<: *job_common
    steps:
      - checkout:
          path: ~/torus-website
      - <<: *step_restore_cache
      - <<: *step_setup_global_packages
      - run:
          name: "Run Tests for torus website"
          command: npm run test:unit
      - <<: *step_save_cache
      # Save test results
      - store_test_results:
          path: ~/test-results
  test-coverage:
    <<: *job_common
    steps:
      - checkout:
          path: ~/torus-website
      - <<: *step_restore_cache
      - <<: *step_setup_global_packages
      - setup_remote_docker
      - run:
          name: "Running unit tests with coverage"
          command: npm run test:coverage-codecov
      # Save coverage artifacts
      - store_artifacts:
          path: coverage
  deploy:
    <<: *job_common
    steps:
      - attach_workspace:
          at: app
      - add_ssh_keys
      - run:
          name: "Deploy Over SSH"
          command: |
            echo '138.68.230.250 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEEQekDY4pm0iOZMDnHGh9ucm/1q1va9DrM6wtbtWFaFjbbh8na4mptJJppYSQ+9A+UROekZdO5QskMo5wubYHQ=' >> ~/.ssh/known_hosts
            cd app/app/
            ssh torus@138.68.230.250 "rm -rf ~/torus-website/*"
            scp -r ./dist torus@138.68.230.250:~/torus-website
  deploy-staging:
    <<: *job_common
    steps:
      - attach_workspace:
          at: app
      - add_ssh_keys
      - run:
          name: "Deploy Over SSH"
          command: |
            echo '138.68.230.250 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEEQekDY4pm0iOZMDnHGh9ucm/1q1va9DrM6wtbtWFaFjbbh8na4mptJJppYSQ+9A+UROekZdO5QskMo5wubYHQ=' >> ~/.ssh/known_hosts
            cd app/app/
            ssh torus@138.68.230.250 "rm -rf ~/staging-torus-website/*"
            scp -r ./dist torus@138.68.230.250:~/staging-torus-website

workflows:
  version: 2
  commit:
    jobs:
      - build
      - test-coverage
      - deploy:
          requires:
            - build
            - test-coverage
          filters:
            branches:
              only:
                - master
      - deploy-staging:
          requires:
            - build
            - test-coverage
          filters:
            branches:
              only:
                - develop
                - chai/metamask-vue