version: 2
job_common: &job_common
  docker:
    - image: circleci/node:10.15.0
  working_directory: ~/torus-website/app
step_save_cache: &step_save_cache
  save_cache:
    key: dependency-cache-{{ checksum "package.json" }}
    paths:
      - node_modules
step_restore_cache: &step_restore_cache
  restore_cache:
    key: dependency-cache-{{ checksum "package.json" }}
step_setup_global_packages: &step_setup_global_packages
  run:
    name: "Set up global packages"
    command: |
      npm install

jobs:
  build:
    <<: *job_common
    steps:
      - checkout:
          path: ~/torus-website
      - <<: *step_restore_cache
      - <<: *step_setup_global_packages
      - run:
          name: "Build code for torus website"
          command: npm run build && npm run buildEmbed
      - <<: *step_save_cache
  unit-test:
    <<: *job_common
    steps:
      - checkout:
          path: ~/torus-website
      - <<: *step_restore_cache
      - <<: *step_setup_global_packages
      - run:
          name: "Run Tests for torus website"
          command: npm run test:unit
      - <<: *step_save_cache
      # Save test results
      - store_test_results:
          path: ~/test-results
  test-coverage:
    <<: *job_common
    steps:
      - checkout:
          path: ~/torus-website
      - <<: *step_restore_cache
      - <<: *step_setup_global_packages
      - setup_remote_docker
      - run:
          name: "Running unit tests with coverage"
          command: npm run test:coverage-codecov
      # Save coverage artifacts
      - store_artifacts:
          path: coverage
  deploy:
    <<: *job_common
    steps:
      - add_ssh_keys
      - checkout:
          path: ~/torus-website
      - run:
          name: "Deploy Over SSH"
          command: |
            echo '165.227.26.16 ecdsa-sha2-nistp256 AAAAB3NzaC1yc2EAAAADAQABAAABAQDBG/QYnk7/FVDiMlI2l66vdKNVC6P2IJZoXmt76FRTEX2iPsg1nYKQzU7bjGRbLaDjPdSt5cXY5UG2ZNFhhed9IM6MlOb9oZ9wNdlIvCFlV1E51hRQdRXCbNtKSZ+sBJKywysWbdapxEaDlDp5fdKip/uhHWN1B3kiZ73fnN5+J6/8z2RhUkk2jjfS/MvRT5HLRCPaCerodXtSnGf54QfITeZ3w+xczwv1jre011sg3wlbpd7kxt6rGsYjPn161GkVxOrJSbci9gqhK/bhsWZruBfxqh0AfjN6JtS2pS/rL9ZIJTEa4ikne4L0QWFzEdZcRF7yVLGzc1jgzrjlgZU9' >> ~/.ssh/known_hosts
            scp -r dist torus@165.227.26.16:~/torus-website

workflows:
  version: 2
  commit:
    jobs:
      - build
      - test-coverage
      - deploy:
          requires:
            - build
            - test-coverage
          filters:
            branches:
              only: chai/metamask-vue
