version: 2
job_common: &job_common
  docker:
    - image: circleci/node:10.15.0
  working_directory: ~/torus-website/app
step_save_cache: &step_save_cache
  save_cache:
    key: dependency-cache-{{ checksum "package.json" }}
    paths:
      - node_modules
step_restore_cache: &step_restore_cache
  restore_cache:
    key: dependency-cache-{{ checksum "package.json" }}
step_setup_global_packages: &step_setup_global_packages
  run:
    name: "Set up global packages"
    command: |
      npm install

jobs:
  build:
    <<: *job_common
    steps:
      - checkout:
          path: ~/torus-website
      - <<: *step_restore_cache
      - <<: *step_setup_global_packages
      - run:
          name: "Build code for torus website"
          command: npm run build
      - persist_to_workspace:
          root: ~/torus-website/
          paths:
            - app
      - <<: *step_save_cache
  unit-test:
    <<: *job_common
    steps:
      - checkout:
          path: ~/torus-website
      - <<: *step_restore_cache
      - <<: *step_setup_global_packages
      - run:
          name: "Run Tests for torus website"
          command: npm run test:unit
      - <<: *step_save_cache
      # Save test results
      - store_test_results:
          path: ~/test-results
  test-coverage:
    <<: *job_common
    steps:
      - checkout:
          path: ~/torus-website
      - <<: *step_restore_cache
      - <<: *step_setup_global_packages
      - setup_remote_docker
      - run:
          name: "Running unit tests with coverage"
          command: npm run test:coverage-codecov
      # Save coverage artifacts
      - store_artifacts:
          path: coverage
  deploy:
    <<: *job_common
    steps:
      - attach_workspace:
          at: app
      - add_ssh_keys
      - run:
          name: "Deploy Over SSH"
          command: |
            echo '165.227.26.16 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBG25I235mTkWa3sbHxzu1rOpDxh4x7Crrbf75+B6Lp9uRhVcjKzhYRbLa1kkrRTrpMuCe5ZvML5QNkXA6d1Lp8Y=' >> ~/.ssh/known_hosts
            cd app/app/
            sudo rm -rf -d ./dist/js/*.map
            scp -r ./dist torus@165.227.26.16:~/torus-website

workflows:
  version: 2
  commit:
    jobs:
      - build
      - test-coverage
      - deploy:
          requires:
            - build
            - test-coverage
          filters:
            branches:
              only:
                - develop
