version: 2
job_common: &job_common
  docker:
    - image: skyuppercut/node-puppeteer:latest
  working_directory: ~/torus-website/app
step_save_cache: &step_save_cache
  save_cache:
    key: dependency-cache-{{ checksum "package.json" }}
    paths:
      - node_modules
step_restore_cache: &step_restore_cache
  restore_cache:
    key: dependency-cache-{{ checksum "package.json" }}
step_setup_global_packages: &step_setup_global_packages
  run:
    name: "Set up global packages"
    command: |
      npm ci

jobs:
  build:
    <<: *job_common
    steps:
      - checkout:
          path: ~/torus-website
      - <<: *step_restore_cache
      - <<: *step_setup_global_packages
      - run:
          name: "Build code for torus website"
          command: |
            npm run update:buildVersion && npm run build && . ./scripts/gitPush.sh
      - persist_to_workspace:
          root: ~/torus-website/
          paths:
            - .
      - <<: *step_save_cache
  build-staging:
    <<: *job_common
    steps:
      - checkout:
          path: ~/torus-website
      - <<: *step_restore_cache
      - <<: *step_setup_global_packages
      - run:
          name: "Build code for torus website"
          command: npm run build:staging
      - persist_to_workspace:
          root: ~/torus-website/
          paths:
            - .
      - <<: *step_save_cache
  unit-test:
    <<: *job_common
    steps:
      - checkout:
          path: ~/torus-website
      - <<: *step_restore_cache
      - <<: *step_setup_global_packages
      - run:
          name: "Run Tests for torus website"
          command: npm run test:unit
      - <<: *step_save_cache
      # Save test results
      - store_test_results:
          path: ~/test-results
  test-coverage:
    <<: *job_common
    steps:
      - checkout:
          path: ~/torus-website
      - <<: *step_restore_cache
      - <<: *step_setup_global_packages
      - setup_remote_docker
      - run:
          name: "Running unit tests with coverage"
          command: npm run test:coverage-codecov
      # Save coverage artifacts
      - store_artifacts:
          path: coverage
  deploy:
    <<: *job_common
    steps:
      - attach_workspace:
          at: ~/torus-website
      - add_ssh_keys
      - run:
          name: "Deploy Over SSH to AWS"
          command: |
            echo $(ls)
            echo $(ls | xargs ls)
            cd app
            . ./scripts/uploadToAws.sh

  deploy-staging:
    <<: *job_common
    steps:
      - attach_workspace:
          at: ~/torus-website
      - add_ssh_keys
      - run:
          name: "Deploy Over SSH"
          command: |
            ssh-keyscan -H staging.tor.us >> ~/.ssh/known_hosts
            cd app/
            ssh torus@staging.tor.us "rm -rf ~/staging-torus-website/*"
            scp -r ./dist torus@staging.tor.us:~/staging-torus-website
  update-iframeIntegrity:
    <<: *job_common
    steps:
      - attach_workspace:
          at: ~/torus-website
      - add_ssh_keys
      - run:
          name: "Update iframe integrity"
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            cd app/
            . ./scripts/updateIframeIntegrity.sh
  update-lambda:
    <<: *job_common
    steps:
      - attach_workspace:
          at: ~/torus-website
      - add_ssh_keys
      - run:
          name: "Update lambda version"
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            cd app/
            . ./scripts/updateLambda.sh

workflows:
  version: 2
  commit:
    jobs:
      - test-coverage
      - build:
          filters:
            branches:
              only:
                - master
      - build-staging:
          filters:
            branches:
              only:
                - develop
      - deploy:
          requires:
            - build
            - test-coverage
          filters:
            branches:
              only:
                - master
      - update-iframeIntegrity:
          requires:
            - deploy
          filters:
            branches:
              only:
                - master
      - update-lambda:
          requires:
            - deploy
          filters:
            branches:
              only:
                - master
      - deploy-staging:
          requires:
            - build-staging
            - test-coverage
          filters:
            branches:
              only:
                - develop
