version: 2
job_common: &job_common
  docker:
    - image: circleci/node:10.15.0
  working_directory: ~/torus-website/app
step_save_cache: &step_save_cache
  save_cache:
    key: dependency-cache-{{ checksum "package.json" }}
    paths:
      - node_modules
step_restore_cache: &step_restore_cache
  restore_cache:
    key: dependency-cache-{{ checksum "package.json" }}
step_setup_global_packages: &step_setup_global_packages
  run:
    name: "Set up global packages"
    command: |
      npm install

jobs:
  build:
    <<: *job_common
    steps:
      - checkout
        path: ~/torus-website
      - <<: *step_restore_cache
      - <<: *step_setup_global_packages
      - run:
          name: "Build code for torus website"
          command: npm run build && npm run buildEmbed
      - <<: *step_save_cache
  unit-test:
    <<: *job_common
    steps:
      - checkout
        path: ~/torus-website
      - <<: *step_restore_cache
      - <<: *step_setup_global_packages
      - run:
          name: "Run Tests for torus website"
          command: npm run test:unit
      - <<: *step_save_cache
      # Save test results
      - store_test_results:
          path: ~/test-results
  test-coverage:
    <<: *job_common
    steps:
      - checkout
        path: ~/torus-website
      - <<: *step_restore_cache
      - <<: *step_setup_global_packages
      - setup_remote_docker
      - run:
          name: "Running unit tests with coverage"
          command: npm run test:coverage
      - run:
          name: "Upload Coverage"
          command: bash <(curl -s https://codecov.io/bash)
      # Save coverage artifacts
      - store_artifacts:
          path: coverage

workflows:
  version: 2
  commit:
    jobs:
      - unit-test
      - test-coverage
